baseurl: 
title: CS768 - Learning with Graphs
subtitle: CS768 IIT Bombay/Fall 2023
author: 
simple_search: http://google.com/search
description: Course Webpage
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Mumbai/India
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: _site/
#   destination: ~/Git/clayh53.github.com/
